local Check = require("Kdm/Util/Check")
local Expansion = require("Kdm/Expansion")
local Gear = require("Kdm/Gear")

---------------------------------------------------------------------------------------------------

local Armor = Gear:new()

---------------------------------------------------------------------------------------------------

function Armor.Init()
    for _, expansion in ipairs(Expansion.All()) do
        for name, stats in pairs(expansion.armorStats or {}) do
            stats.isArmor = true
            Armor:new( { name = name, stats = stats } )
        end
    end
end

---------------------------------------------------------------------------------------------------

function Armor:__tostring()
    return string.format("%s (%d/%d/%d/%d/%d)", self.name, self.stats.head, self.stats.arms, self.stats.body, self.stats.waist, self.stats.legs)
end

---------------------------------------------------------------------------------------------------

return Armor
