local Check = require("Kdm/Util/Check")
local Expansion = require("Kdm/Expansion")
local Gear = require("Kdm/Gear")

---------------------------------------------------------------------------------------------------

local Armor = Gear:new()

---------------------------------------------------------------------------------------------------

function Armor.Init()
    Armor.armor = {}
    for _, expansion in ipairs(Expansion.All()) do
        for name, stats in pairs(expansion.armorStats or {}) do
            if Armor.armor[name] then
                assert(false, string.format("Armor %s was already registered", name))
            end
            Armor.armor[name] = Armor:new( { name = name, stats = stats } )
        end
    end
end

---------------------------------------------------------------------------------------------------

function Armor.Get(armor)
    return Armor.armor[armor]
end

---------------------------------------------------------------------------------------------------

function Armor:__tostring()
    return string.format("%s (%d/%d/%d/%d/%d)", self.name, self.stats.head, self.stats.arms, self.stats.body, self.stats.waist, self.stats.legs)
end

---------------------------------------------------------------------------------------------------

return {
    Init = Armor.Init,
    Get = Armor.Get,
}
