local Check = require("Kdm/Util/Check")
local Expansion = require("Kdm/Expansion")
local Gear = require("Kdm/Gear")
local log = require("Kdm/Log").ForModule("Weapon")

---------------------------------------------------------------------------------------------------

local Weapon = Gear:new()

---------------------------------------------------------------------------------------------------

function Weapon.Init()
    log:Debugf("Weapon.Init()")
    for _, expansion in ipairs(Expansion.All()) do
        log:Debugf("Processing expansion %s", expansion.name)
        for name, stats in pairs(expansion.weaponStats or {}) do
            stats.isWeapon = true
            Weapon:new({
                name = name,
                stats = stats,
            })
        end
    end
    log:Debugf("Weapon.Init() done")
end

---------------------------------------------------------------------------------------------------

function Weapon:__tostring()
    return string.format("%s[%s] (%d/%d/%d)", self.name, self.canonicalName, self.stats.speed, self.stats.accuracy, self.stats.strength)
end

---------------------------------------------------------------------------------------------------

return {
    Init = Weapon.Init,
}
